
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: Tinyurl_development
  username: postgres
  password: postgres
  
test:
  <<: *default
  database: Tinyurl_test

production:
  <<: *default
  database: Tinyurl_production
  username: Tinyurl
  password: <%= ENV['TINYURL_DATABASE_PASSWORD'] %>
